### ISSUE TITLE
shelf is not registered on import

### ISSUE THREAD

**Issue by Aethelflaed** [inventaire/inventaire#436]
When importing books, we have the possibility to select one or several shelves in the settings part (№3) just before the batch import.

This particular settings does not appear to be persisted in the imported items.

On a related note, most of my books end-up with "Cannot read property 'toString' of undefined" when importing, but I guess it's because of a missing ISBN, and I have a few for which it simply prints "request error" (but for those the ISBN is present).

Of the few successfully imported items, I also noticed a duplicated author (`inv:80ad2bc4c59713a69196f5cecb03cb5d`, `inv:80ad2bc4c59713a69196f5cecb040301`, and `inv:80ad2bc4c59713a69196f5cecb03862b`).

I know this may be a bother to point out different problems on the same issue, but this is mainly to report the shelf-related one. I think the other problem may be better discussed in an open-ended discussion, do you have a mailing-list or chatroom somewhere I could join?

**Comment by maxlath** [comment]
we do have chat rooms, see https://wiki.inventaire.io/wiki/Communication-channels?lang=en#chats

**Comment by maxlath** [comment]
the `toString` error should have been fixed by 36cd8d5 (now online), but I couldn't find the problem with the shelves: could you retry to import one with a shelf and see if that works now?

I merged the duplicated authors (fyi, we are working on making that operation available to non-admin users #91)

**Comment by Aethelflaed** [comment]
The shelf has been set for only one item (80ad2bc4c59713a69196f5cecb149263), but this time a whole lot more books got imported (basically all the books with missing ISBN)

I still have a few (4) request error, but I see that I don't have the same ISBN as any of the edition of `inv:a8f43fc184768b0ad5cbe0b1d433cd8e`, so that may be the reason. What is the service request to check the ISBN?
